check email before push

diff --git a/bin/ggph b/bin/ggph
--- a/bin/ggph
+++ b/bin/ggph
@@ -1,3 +1,9 @@
 #!/bin/bash
 
+if ! git check-email; then
+    echo
+    echo "Aborting push; please fix email first."
+    exit $?
+fi
+
 exec git push "$@"
