Fix to honour branch.$branch.merge

diff --git a/bin/ggup b/bin/ggup
--- a/bin/ggup
+++ b/bin/ggup
@@ -1,6 +1,30 @@
 #!/bin/bash
 
-# git upstream - figure out ref of upstream branch
+# Git UPstream - figure out ref of local branch's upstream remote/branch
+
+me=`basename $0`
+
+usage () {
+    # Call as: usage [EXITCODE] [USAGE MESSAGE]
+    exit_code=1
+    if [[ "$1" == [0-9] ]]; then
+        exit_code="$1"
+        shift
+    fi
+    if [ -n "$1" ]; then
+        echo "$*" >&2
+        echo
+    fi
+
+    cat <<EOF >&2
+Usage: $me [<local branch>]
+Outputs the upstream remote/branch for a given local branch,
+if it can be calculated.
+
+The local branch defaults to HEAD.
+EOF
+    exit "$exit_code"
+}
 
 get_svn_upstream () {
     if ! [ -d "$root/.git/svn" ]; then
@@ -49,19 +73,31 @@ get_svn_upstream () {
 
 get_upstream () {
     # If the upstream is explicitly specified in config, we honor that.
-    localhead="`git head`"
-    remotebranchconf="branch.$localhead.remote"
-    upstream=$(git config "$remotebranchconf")
-    if [ -n "$upstream" ]; then
-        if git rev-parse "$upstream" >/dev/null 2>&1; then
-            return
+    local_branch="$1"
+    upstream_remote_conf="branch.$local_branch.remote"
+    upstream_remote=$(git config "$upstream_remote_conf")
+    if [ -n "$upstream_remote" ]; then
+        upstream_branch_conf="branch.$local_branch.merge"
+        upstream_branch=$(git config "$upstream_branch_conf")
+        if [ -n "$upstream_branch" ]; then
+            upstream_branch="${upstream_branch#refs/heads/}"
+            if [ "$upstream_remote" = '.' ]; then
+                upstream="$upstream_branch"
+            else
+                upstream="$upstream_remote/$upstream_branch"
+            fi
+            if git rev-parse "$upstream" >/dev/null 2>&1; then
+                return
+            fi
+        else
+            upstream="$upstream_remote/$local_branch"
+            if git rev-parse "$upstream_remote" >/dev/null 2>&1; then
+                return
+            else
+                echo "Couldn't determine upstream branch from $remotebranchconf = $upstream" >&2
+                exit 1
+            fi
         fi
-        upstream="$upstream/$localhead"
-        if git rev-parse "$upstream" >/dev/null 2>&1; then
-            return
-        fi
-        echo "Couldn't determine upstream branch from $remotebranchconf = $upstream" >&2
-        exit 1
     fi
 
     if ! get_svn_upstream; then
@@ -70,7 +106,7 @@ get_upstream () {
         # and remote branches have the same name.  'origin' is just
         # the name that git uses by default to refer to the
         # repository that you cloned from.
-        upstream=origin/$localhead
+        upstream=origin/$local_branch
     fi
 }
 
@@ -79,14 +115,23 @@ if ! [ -d "$root" ]; then
     exit 1
 fi
 
-get_upstream
+if [ "$1" == '-h' ] || [ "$1" == '--help' ] || [ $# -gt 1 ]; then
+    usage 0
+fi
+
+local_branch="$1"
+if [ $# -eq 0 ]; then
+    local_branch="`git head`"
+fi
+
+get_upstream "$local_branch"
 
 if ! git rev-parse "$upstream" >/dev/null 2>&1; then
     cat <<EOF >&2
 Best guess '$upstream' was invalid.
 Maybe you should do:
 
-   git config branch.$localhead.remote \$remote
+   git config branch.$local_branch.remote \$remote
 
 Couldn't figure out upstream ref; aborting.
 EOF
@@ -94,3 +139,4 @@ EOF
 fi
 
 echo "$upstream"
+
