tag-patchset: fix bugs and add --force

diff --git a/bin/git-tag-patchset b/bin/git-tag-patchset
--- a/bin/git-tag-patchset
+++ b/bin/git-tag-patchset
@@ -13,11 +13,18 @@ usage () {
     fi
 
     cat <<EOF >&2
-Usage: $me [PATCH-SET-NUM] [COMMIT-ISH]
+Usage: $me [-f|--force] [PATCH-SET-NUM] [COMMIT-ISH]
 
-Make a tag for a new or given patch set.  The tag will be named in this format:
+Make a tag for a new or given patch set for the current branch which
+points to COMMIT-ISH.
+
+The tag will be named in this format:
 
     \${current_branch}/PS\${num}
+
+Options:
+
+  -f, --force   Force-update an existing tag to point to COMMIT-ISH
 EOF
     exit 1
 }
@@ -29,20 +36,23 @@ find_latest_patch_set () {
         tail -n 1
 }
 
-check_branch_exists () {
-    if ! git rev-parse --quiet --verify "$branch" >/dev/null; then
-        echo >&2 "Branch $branch didn't exist; aborting."
-        exit 1
-    fi
-}
-
 main () {
+    case "$1" in
+        -f|--force)
+            force=-f
+            shift
+            ;;
+    esac
+
     if [ $# -gt 2 ]; then
         usage
     fi
 
-    branch="${2:-`git head`}"
-    check_branch_exists
+    if ! branch="`git head`"; then
+        echo >&2 "Couldn't figure out current branch!  Aborting."
+        exit 1
+    fi
+    target="${2:-$branch}"
 
     tag_prefix="$branch/PS"
 
@@ -60,15 +70,14 @@ main () {
 
     if git rev-parse --quiet --verify "$tag" >/dev/null; then
         current=$( git rev-parse "$tag")
-        if [[ "$current" == $(git rev-parse "$branch") ]]; then
-            echo "$tag already points to $branch"
+        if [[ "$current" == $(git rev-parse "$target") ]]; then
+            echo "$tag already points to $target"
         else
-            echo "$tag already points to $(ggde $current); will force update ..."
-            git tag -f "$tag" "$branch"
+            git tag $force "$tag" "$target"
         fi
     else
-        if git tag "$tag" "$branch"; then
-            echo "Tagged $branch as $tag"
+        if git tag "$tag" "$target"; then
+            echo "Tagged $target as $tag"
         fi
     fi
 }
