allow skipping push/pull

diff --git a/bin/git-dwim b/bin/git-dwim
--- a/bin/git-dwim
+++ b/bin/git-dwim
@@ -54,6 +54,20 @@ show_upstream_info () {
     git remote -v show -n "$1"
 }
 
+confirm_action () {
+    action="$1"
+
+    while true; do
+        echo    "Enter 'y' to $action,"
+        echo -n "      's' to skip, or Control-C to abort > "
+        read answer
+        case "$answer" in
+            y) return 0 ;;
+            s) return 1 ;;
+        esac
+    done
+}
+
 pull_from_upstream () {
     local upstream="$1"
 
@@ -61,8 +75,7 @@ pull_from_upstream () {
     echo -e "\e[1;31m$head is behind $upstream by $behind commits:\e[0m"
     git log HEAD.."$upstream"
     echo
-    echo -n "Press Enter to pull missing commits from $upstream, or Control-C to abort > "
-    read
+    confirm_action "pull missing commits from $upstream" || return
     echo "Running git pull ..."
     if ! git pull; then
         echo "git pull failed; aborting.  Please manually fix and re-run." >&2
@@ -77,8 +90,7 @@ push_to_upstream () {
     echo -e "\e[1;33m$head is ahead of $upstream by $ahead commits.\e[0m"
     git log "$upstream"..HEAD
     echo
-    echo -n "Press Enter to push new commits to $upstream, or Control-C to abort > "
-    read
+    confirm_action "push new commits to $upstream" || return
     if ! git push; then
         echo "git push failed; aborting.  Please manually fix and re-run." >&2
         exit 1
