fix pushing to github

diff --git a/bin/git-dwim b/bin/git-dwim
--- a/bin/git-dwim
+++ b/bin/git-dwim
@@ -40,6 +40,13 @@ EOF
     fi
 }
 
+parse_upstream () {
+    local upstream="$1"
+
+    remote="${upstream%/*}"
+    remote_branch="${upstream#*/}"
+}
+
 compare_with_upstream () {
     local upstream="$1"
 
@@ -74,11 +81,14 @@ pull_from_upstream () {
     echo
     echo -e "\e[1;31m$head is behind $upstream by $behind commits:\e[0m"
     git log HEAD.."$upstream"
+
     echo
     confirm_action "pull missing commits from $upstream" || return
-    echo "Running git pull ..."
-    if ! git pull; then
-        echo "git pull failed; aborting.  Please manually fix and re-run." >&2
+
+    args="$remote $remote_branch"
+    echo "Running git pull $args ..."
+    if ! git pull $args; then
+        echo "git pull $args failed; aborting.  Please manually fix and re-run." >&2
         exit 1
     fi
 }
@@ -89,10 +99,13 @@ push_to_upstream () {
     echo
     echo -e "\e[1;33m$head is ahead of $upstream by $ahead commits.\e[0m"
     git log "$upstream"..HEAD
+
     echo
     confirm_action "push new commits to $upstream" || return
-    if ! git push; then
-        echo "git push failed; aborting.  Please manually fix and re-run." >&2
+
+    args="$remote $head"
+    if ! git push $args; then
+        echo "git push $args failed; aborting.  Please manually fix and re-run." >&2
         exit 1
     fi
 }
@@ -112,8 +125,7 @@ sync_with_upstream () {
     local upstream="$1"
 
     compare_with_upstream "$upstream"
-
-    remote="${upstream#*/}"
+    parse_upstream "$upstream"
     show_upstream_info "$remote"
 
     if [ "$behind" != 0 ]; then
