check git on $PATH

diff --git a/.cfg-post.d/git b/.cfg-post.d/git
--- a/.cfg-post.d/git
+++ b/.cfg-post.d/git
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if ! which git >&/dev/null; then
+    echo "git not found; aborting .cfg-post.d/git" >&2
+    exit 1
+fi
+
 if which zsh >&/dev/null; then
   zsh -c zrec
 fi
